{"timestamp": "2025-05-02T22:03:52.533534", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 9104, "thread": "MainThread"}
{"timestamp": "2025-05-02T22:04:00.071214", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 9104, "thread": "MainThread"}
{"timestamp": "2025-05-02T22:04:00.071566", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 9104, "thread": "MainThread"}
{"timestamp": "2025-05-02T22:04:02.269498", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 9104, "thread": "MainThread"}
{"timestamp": "2025-05-02T22:04:06.799527", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 9104, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-02T22:04:06.801490", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 9104, "thread": "Thread-2 (process_request_thread)"}
